services:
  postgres:
    restart: always
    ports: []

  redis:
    restart: always
    ports: []

  flyway:
    restart: "no"

  api:
    restart: always
    environment:
      APP_ENV: prod
      SPRING_PROFILES_ACTIVE: prod
      CACHE_TYPE: redis
    ports: []

  web:
    restart: always
    environment:
      APP_ENV: prod
      NODE_ENV: production
    ports:
      - "${WEB_PORT}:3000"
